<?php

/**
 * @file
 * Contains social_post_twitter.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function social_post_twitter_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if(user_can_grant_permission()) {
    // Add a button to authorize twitter autoposting.
    $form['social_post_twitter'] = array(
      '#type' => 'details',
      '#title' => t('Social Post Twitter'),
      '#open' => TRUE
    );
    $form['social_post_twitter']['button'] = array(
      '#type' => 'link',
      '#title' => t("Add an account"),
      '#attributes' => array(
        'class' => array('button'),
      ),
      '#url' => Url::fromRoute('social_post_twitter.redirect_to_twitter')
    );
  }
}

/**
 * Check if the user is allowed to grant permission for autoposting.
 *
 * @return boolean
 */
function user_can_grant_permission() {
  $currentUser = \Drupal::currentUser();
  $routeMatch = \Drupal::service('current_route_match');

  // If the current user has permission to autopost content to social networks
  // and the current user id is the same as the user id of parameter
  if($currentUser->hasPermission('perform twitter autoposting tasks')
    && $currentUser->id() == $routeMatch->getParameter('user')->id() ) {
    return true;
  }

  return false;
}
